# Content to insert in the placeholders
pages = {
    "apple-letter": {
        "title": "Apple Bubble Letter",
        "tagline": "Modelling challenge for external company",
        "client": "Personal Project",
        "type": "Alias Modelling",
        "year": "2020",
        "image_folder": "images/apple-letter/",
        "description": "Enhance your 3D design experience with Autodesk Alias SubD. Learn how Shinji Pons improved user integration, streamlining workflows and reducing learning curves for efficient, high-quality modeling.",
        "paragraph_1": "As part of an interview loop, I did this bubble letter of a capital R. The brief was to model a bubble letter with a circular profile while avoiding flat areas at the intersection and, of course, maintaining perfect continuity and clean geometry.",
        "paragraph_2": "The biggest challenge in this exercise to avoid flat planes in the transition areas where the main pipes of the bubble letter meet.",
    },
    "louvre-abu-dhabi": {
        "title": "Louvre Abu Dhabi",
        "tagline": "Signage inspired by architecture",
        "client": "Ateliers Jean Nouvel",
        "type": "Graphic Design",
        "year": "2012",
        "description": "Discover Shinji Pons' work on the Louvre Abu Dhabi, where he collaborated on typographic signage and icon design, ensuring clarity and elegance across French, English, and Arabic for a global audience.",
        "image_folder": "images/louvre-abu-dhabi/",
        "paragraph_1": "While at Ateliers Jean Nouvel, I worked on the typographic signage and icon design for the Louvre Abu Dhabi museum under the the creative direction of Philippe Apeloig and Clovis Vallois.",
        "paragraph_2": "To accompany the building's unique design, Philippe Apeloig had devised a system using the dome's light patterns. The challenge was to make the icons understandable from every culture.",
    },
    "lego-digital-designer-pro": {
        "title": "LEGO Digital Designer Pro",
        "tagline": "CAD software for LEGO sets",
        "client": "The LEGO Group",
        "type": "UX Design",
        "year": "2021",
        "description": "Discover how Shinji Pons enhanced the LEGO Digital Designer Pro, streamlining workflows and automating tasks to boost efficiency and reduce costs for LEGO's virtual set design process.",
        "image_folder": "images/ldd-pro",
        "paragraph_1": "While at the LEGO Group, I designed tools and workflows for LEGO's in-house software for designing virtual LEGO sets and authoring digital building instructions.",
        "paragraph_2": "My role was to improve efficiency and reducing costs for the business by streamlining processes and automating tedious tasks.",
    },
    "alias-subd": {
        "title": "Autodesk Alias SubD",
        "tagline": "Making Alias better for everyone",
        "client": "Autodesk",
        "type": "UX Design",
        "year": "2019",
        "description": "Discover how Shinji Pons improved Autodesk Alias SubD's user experience, integrating seamlessly with NURBS tools to streamline 3D modeling workflows and reduce learning curves for efficient, high-quality design.",
        "image_folder": "images/alias-subd",
        "paragraph_1": "Autodesk Alias is an industry-leading 3D CAD software that empowers designers to create high-quality, manufacturable surfaces. I had the privilege of designing the user experience for the SubD toolset within Alias. My work ensured seamless integration with the existing NURBS tools, making the entire design process more efficient and intuitive.",
        "paragraph_2": "Thanks to these tools, new users can produce 3D models that can be refined and reworked by more experienced users without ever exporting anything, or compromising on quality.",
    },
    "dynamo-for-alias": {
        "title": "Dynamo for Alias",
        "tagline": "Augmenting Alias with generative algorithms",
        "client": "Autodesk",
        "type": "UX Design",
        "year": "2017",
        "description": "Discover Shinji Pons' integration of Dynamo with Autodesk Alias, enabling designers to automate complex surface modeling, enhancing efficiency and reducing creative waste in automotive design.",
        "image_folder": "images/dynamo-for-alias",
        "paragraph_1": "While at Autodesk, I worked on the integration of Dynamo, a visual programming environment, into Alias. This workflow improvement empowered designers to leverage scripting to create complex surfaces that would be otherwise too time-consuming to model.",
        "paragraph_2": "My role was to make sure that Dynamo was relatively well integrated into Alias, and that the user experience was not too cumbersome.",
    },
    "david-bowie": {
        "title": "Nothing has Changed",
        "tagline": "Artworking for David Bowie's album",
        "client": "Barnbrook and David Bowie",
        "type": "Graphic Design",
        "year": "2014",
        "description": "Explore Shinji Pons' contribution to the David Bowie album project during his internship at Barnbrook, focusing on precision in layout adjustments and visual alignment, enhancing his design skills.",
        "image_folder": "images/david-bowie",
        "paragraph_1": "My role was artworking for a David Bowie album. This internship was an important step in my career, emphasizing the significance of detail and teamwork in design.",
        "paragraph_2": "It has motivated me to further my skills and pursue my career with renewed focus.",
    },
    "basiljs": {
        "title": "Computational Typography in InDesign",
        "tagline": "Automating tasks in InDesign with code",
        "client": "Personal Project",
        "type": "Graphic Design",
        "year": "2014",
        "description": "Discover how Shinji Pons used Basil.js to automate and innovate in Adobe InDesign, transforming manual, tedious tasks into efficient, error-free processes, enhancing creative possibilities in computational typography.",
        "image_folder": "images/basiljs",
        "paragraph_1": "My final major project at the London College of Communication was around exploring scripting inside of Adobe InDesign using a library called basil.js.",
        "paragraph_2": "While working on Modulo, my layered typeface, I realized how tedious and inefficient it was to manually overlay hundreds of individual text frames for my type tests. I understood that code could be used for creative purposes and that it was an incredible way to automate tasks and reduce errors.",
    },
    "ipod-shuffle": {
        "title": "iPod Shuffle Alias Model",
        "tagline": "Accurate modelling with G3 continuity",
        "client": "Personal Project",
        "type": "Alias 3D Modelling",
        "year": "2021",
        "description": "Explore Shinji Pons' precise modeling of the fourth-generation iPod Shuffle in Alias, emphasizing G3 continuity, detailed surface transitions, and functional elements like the power button and audio jack for enhanced user experience.",
        "image_folder": "images/ipod-shuffle",
        "paragraph_1": "I purchased an iPod Shuffle on eBay and modeled it Alias while ensuring G3 continuity in even the smallest of fillets.",
        "paragraph_2": "The finished file has a power button and an accurately modelled 1/8\" female audio jack. All the surface transitions are G3.",
    },
    "modulo": {
        "title": "Modulo",
        "tagline": "Multi-layer geometric typeface",
        "client": "Personal Project",
        "type": "Typeface Design",
        "year": "2014",
        "description": "Explore Shinji Pons' creation of Modulo, a typeface based on a 128-unit square grid. Learn about his meticulous design process, overcoming technical challenges, and gaining expertise in Bézier splines and professional-grade typeface development.",
        "image_folder": "images/modulo",
        "paragraph_1": "Modulo is a free and open-source typeface based on a 128 units square grid. I wanted to learn the intricate details of typeface design and development, while making something I could use for myself in future design work.",
        "paragraph_2": "I had to restart making all 168 font files five or six times after realizing that I fell in technical pitfalls such as using incorrect UPM sizes, path directions, undesired optical corrections in Glyphs, forgetting glyphs...",
    },
    "corvette": {
        "title": "High quality 3D model of a Chevrolet Corvette C6",
        "tagline": "Modelling a full car in Blender",
        "client": "Personal Project",
        "type": "3D Modelling",
        "year": "2022",
        "description": "Explore Shinji Pons' high-quality 3D model of the Chevrolet Corvette C6, created using advanced modeling techniques in Blender. Learn how he mastered surface quality and polygonal modeling through self-paced learning.",
        "image_folder": "images/corvette",
        "paragraph_1": "After working on the Autodesk Alias SubD toolset, I wanted to improve my polygonal modelling skills. I completed a self-paced course called Master Car Creation in Blender by CGMasters. The course focuses on advanced modelling techniques to achieve the highest quality in terms of reflections.",
        "paragraph_2": "Compared to Alias, Blender was quicker and more productive at the beginning of the process. Modelling and shading all surfaces in one software package is great but I did miss the flawless quality of NURBS surfaces."
    },
    "midjourney": {
        "title": "My Midjourney portfolio",
        "tagline": "Learning to use Midjourney",
        "client": "Personal Project",
        "type": "AI Imagery",
        "year": "2024",
        "description": "Explore Shinji's collection of images generated using Midjourney.",
        "image_folder": "images/midjourney",
        "paragraph_1": "I just type words.",
        "paragraph_2": "And pretty images come out."
    },
    "lovers-dew": {
        "title": "Lovers' Dew 3D Rendering",
        "tagline": "3D Modelling and Rendering of a Perfume Bottle for a US brand",
        "client": "Matteo Parfums",
        "type": "3D Rendering",
        "year": "2024",
        "description": "Discover Shinji's 3D modelling and rendering work for Matteo Parfums.",
        "image_folder": "images/lovers-dew",
        "paragraph_1": "Matteo Parfums reached out to for help on their 3D rendering project for their new scent Lovers' Dew. I modelled the perfume bottle from schematics in Plasticity, set the creative direction and rendered the images using Blender Cycles.",
        "paragraph_2": "<a href=\"../blog/lovers-dew-case-study.html\">Learn more about the project</a>"
    }
}

# in vase I need to add another new project...

# "david-bowie": {
#     "title": "",
#     "tagline": "",
#     "client": "",
#     "type": "",
#     "year": "",
#     "description": "",
#     "image_folder": "images/",
#     "paragraph_1": "",
#     "paragraph_2": "",
#     "paragraph_3": "",
#     "paragraph_4": ""
# }